config/urls.py
from django.contrib import admin
from django.urls import path, include
from oneup import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('oneup/', include('oneup.urls')),
    path('common/', include('common.urls')),
]

oneup/urls.py
from django.urls import path

from . import views

app_name = 'oneup'

urlpatterns = [
    path('outsourcing/', views.index, name='outsourcing'),
    path('manufacture/', views.manufacturer, name='manufacture'),
    path('logistics/', views.logistics, name='logistics'),
    path('as/', views.after, name='after'),
    path('main/', views.main, name='main'),
    path('deny/', views.deny, name='deny'),
    path('as_service/', views.as_create, name='as_create'),
    path('export1/', views.export1, name='out_export'),
    path('export2/', views.export2, name='make_export'),
    path('export3/', views.export3, name='log_export'),
    path('export4/', views.export4, name='as_export'),
    ]

oneup/models.py
from django.db import models

class Outsourcing(models.Model):
    ossn = models.CharField(max_length=50, null=True, blank=True)
    osqu = models.CharField(max_length=50, null=True, blank=True)
    osdate = models.DateTimeField()

    def __str__(self):
        return self.ossn

class Manufacture(models.Model):
    proname = models.CharField(max_length=50, null=True, blank=True)
    mfsn = models.CharField(max_length=50, null=True, blank=True)
    origin = models.CharField(max_length=50, null=True, blank=True)
    halfpro = models.CharField(max_length=50, null=True, blank=True)
    workercode = models.CharField(max_length=50, null=True, blank=True)
    mfsta = models.CharField(max_length=50, null=True, blank=True)
    mfdate = models.DateTimeField()

    def __str__(self):
        return self.proname

class Logistics(models.Model):
    logname = models.CharField(max_length=50, null=True, blank=True)
    logsn = models.CharField(max_length=50, null=True, blank=True)
    wh = models.CharField(max_length=50, null=True, blank=True)
    dis = models.CharField(max_length=50, null=True, blank=True)
    agen = models.CharField(max_length=50, null=True, blank=True)
    logcustom = models.CharField(max_length=50, null=True, blank=True)

    def __str__(self):
        return self.logname

class As(models.Model):
    asname = models.CharField(max_length=50)
    ph = models.CharField(max_length=50)
    pronumber = models.CharField(max_length=50)
    assta = models.CharField(max_length=50, null=True, blank=True)
    record = models.FileField(null=True, blank=True)
    asdate = models.DateTimeField()

    def __str__(self):
        return self.asname

oneup/forms.py
from django import forms
from oneup.models import As

class AsForm(forms.ModelForm):
    class Meta:
        model = As
        fields = ['asname', 'ph', 'pronumber']
        labels = {
            'asname': '이름',
            'ph': '전화번호',
            'pronumber': '제품번호',
        }

oneup/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Outsourcing, Manufacture, As, Logistics
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib import messages
from django.utils import timezone
from .forms import AsForm
from django.core.paginator import Paginator
from django.db.models import Q
from oneup.resources import OutResource, ManResource, LogResource, AsResource

@login_required(login_url='common:login')
@permission_required('oneup.view_outsourcing', login_url='oneup:deny', raise_exception=False)
def index(request):
    """
       out 목록 출력
       """
    # 입력 파라미터
    page = request.GET.get('page', '1')  # 페이지
    kw = request.GET.get('kw', '')  # 검색어
    so = request.GET.get('so', 'recent')  # 정렬기준

    # 정렬
    if so == 'code':
        outsourcing_list = Outsourcing.objects.order_by('ossn', '-osdate')
    elif so == 'que':
        outsourcing_list = Outsourcing.objects.order_by('-osqu', '-osdate')
    else:  # recent
        outsourcing_list = Outsourcing.objects.order_by('-osdate')

        # 조회
    if kw:
        outsourcing_list = outsourcing_list.filter(
            Q(ossn__icontains=kw) |  # 부품코드 검색
            Q(osqu__icontains=kw) |  # 납품수량 검색
            Q(osdate__icontains=kw)  # 납품일시 검색
        ).distinct()

        # 페이징처리
    paginator = Paginator(outsourcing_list, 10)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)
    context = {'outsourcing_list': page_obj, 'page': page, 'kw': kw, 'so': so}  # page, kw, so가 추가되었다.
    return render(request, 'oneup/outsourcing_list.html', context)

@login_required(login_url='common:login')
@permission_required('oneup.view_manufacture', login_url='oneup:deny', raise_exception=False)
def manufacturer(request):
    """
       manu 목록 출력
       """
    # 입력 파라미터
    page = request.GET.get('page', '1')  # 페이지
    kw = request.GET.get('kw', '')  # 검색어
    so = request.GET.get('so', 'recent')  # 정렬기준

    # 정렬
    if so == 'pro':
        manufacture_list = Manufacture.objects.order_by('-proname', '-mfdate')
    elif so == 'mfsn':
        manufacture_list = Manufacture.objects.order_by('-mfsn', '-mfdate')
    elif so == 'ori':
        manufacture_list = Manufacture.objects.order_by('-origin', '-mfdate')
    elif so == 'half':
        manufacture_list = Manufacture.objects.order_by('-halfpro', '-mfdate')
    elif so == 'work':
        manufacture_list = Manufacture.objects.order_by('-workercode', '-mfdate')
    elif so == 'mfst':
        manufacture_list = Manufacture.objects.order_by('-mfsta', '-mfdate')
    else:  # recent
        manufacture_list = Manufacture.objects.order_by('-mfdate')

        # 조회
    if kw:
        manufacture_list = manufacture_list.filter(
            Q(proname__icontains=kw) |  # 제품명 검색
            Q(mfsn__icontains=kw) |  # 시리얼넘버 검색
            Q(origin__icontains=kw) |  # 원자재 검색
            Q(halfpro__icontains=kw) |  # 반제품 검색
            Q(workercode__icontains=kw) |  # 작업자코드 검색
            Q(mfsta__icontains=kw) |  # 제작상태 검색
            Q(mfdate__icontains=kw)  # 업데이트 일시 검색
        ).distinct()

    # 페이징처리
    paginator = Paginator(manufacture_list, 10)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)
    context = {'manufacture_list': page_obj, 'page': page, 'kw': kw, 'so': so}  # page, kw, so가 추가되었다.
    return render(request, 'oneup/manufacture_list.html', context)

@login_required(login_url='common:login')
@permission_required('oneup.view_logistics', login_url='oneup:deny', raise_exception=False)
def logistics(request):
    """
       log 목록 출력
       """
    # 입력 파라미터
    page = request.GET.get('page', '1')  # 페이지
    kw = request.GET.get('kw', '')  # 검색어
    so = request.GET.get('so', 'logn')  # 정렬기준

    # 정렬
    if so == 'logcu':
        logistics_list = Logistics.objects.order_by('-logcustom')
    elif so == 'logsn':
        logistics_list = Logistics.objects.order_by('-logsn')
    elif so == 'wh':
        logistics_list = Logistics.objects.order_by('-wh')
    elif so == 'dis':
        logistics_list = Logistics.objects.order_by('-dis')
    elif so == 'agen':
        logistics_list = Logistics.objects.order_by('-agen')
    else: # logn
        logistics_list = Logistics.objects.order_by('-logname')

        # 조회
    if kw:
        logistics_list = logistics_list.filter(
            Q(logcustom__icontains=kw) |  # 고객 검색
            Q(logsn__icontains=kw) |  # 시리얼넘버 검색
            Q(wh__icontains=kw) |  # 보관창고 검색
            Q(dis__icontains=kw) |  # 총판 검색
            Q(agen__icontains=kw) |  # 대리점 검색
            Q(logname__icontains=kw)  # 제품명 검색
        ).distinct()

    # 페이징처리
    paginator = Paginator(logistics_list, 10)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)
    context = {'logistics_list': page_obj, 'page': page, 'kw': kw, 'so': so}  # page, kw, so가 추가되었다.
    return render(request, 'oneup/logistics_list.html', context)

@login_required(login_url='common:login')
@permission_required('oneup.view_as', login_url='oneup:deny', raise_exception=False)
def after(request):
    """
       as 목록 출력
       """
    # 입력 파라미터
    page = request.GET.get('page', '1')  # 페이지
    kw = request.GET.get('kw', '')  # 검색어
    so = request.GET.get('so', 'recent')  # 정렬기준

    # 정렬
    if so == 'asname':
        as_list = As.objects.order_by('asname', '-asdate')
    elif so == 'pronu':
        as_list = As.objects.order_by('pronumber', '-asdate')
    elif so == 'assta':
        as_list = As.objects.order_by('assta', '-asdate')
    else: # recent
        as_list = As.objects.order_by('-asdate')

        # 조회
    if kw:
        as_list = as_list.filter(
            Q(asname__icontains=kw) |  # 고객명 검색
            Q(ph__icontains=kw) |  # 전화번호 검색
            Q(pronumber__icontains=kw) |  # 제품번호 검색
            Q(assta__icontains=kw) |  # A/S현황 검색
            Q(record__icontains=kw) |  # 통화녹음 검색
            Q(asdate__icontains=kw)  # 등록일시 검색
        ).distinct()

    # 페이징처리
    paginator = Paginator(as_list, 10)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)
    context = {'as_list': page_obj, 'page': page, 'kw': kw, 'so': so}  # page, kw, so가 추가되었다.
    return render(request, 'oneup/as_list.html', context)

@login_required(login_url='common:login')
def main(request):
    """
        메인 페이지 : 이동할 DB 선택
           """
    return render(request, 'oneup/main.html')

def deny(request):
    """
        권한없음
                   """
    return render(request, 'oneup/deny.html')

def as_create(request):
    """
    as 정보입력
    """
    if request.method == 'POST':
        form = AsForm(request.POST)
        if form.is_valid():
            As = form.save(commit=False)
            As.asdate = timezone.now()
            As.save()
            messages.success(request, '제출해 주셔서 감사합니다!')
            return redirect('oneup:as_create')
    else:
        form = AsForm()
    context = {'form': form}
    return render(request, 'oneup/as_form.html', context)

def export1(request):
    out_resource = OutResource()
    dataset = out_resource.export()
    response = HttpResponse(dataset.xls, content_type='text/xls')
    response['Content-Disposition'] = 'attachment; filename="outsourcing.xls"'
    return response

def export2(request):
    man_resource = ManResource()
    dataset = man_resource.export()
    response = HttpResponse(dataset.xls, content_type='text/xls')
    response['Content-Disposition'] = 'attachment; filename="manufacture.xls"'
    return response

def export3(request):
    log_resource = LogResource()
    dataset = log_resource.export()
    response = HttpResponse(dataset.xls, content_type='text/xls')
    response['Content-Disposition'] = 'attachment; filename="logistics.xls"'
    return response

def export4(request):
    as_resource = AsResource()
    dataset = as_resource.export()
    response = HttpResponse(dataset.xls, content_type='text/xls')
    response['Content-Disposition'] = 'attachment; filename="AS.xls"'
    return response

templates/oneup/as_form.html
<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css">
<div class="img-fluid" style="background-image: url('https://res.cloudinary.com/dgb2e2npb/image/upload/v1616504856/guillaume-de-germain-IzZSdv_x8VY-unsplash_wrwpld.jpg');
      height: 100vh; background-position: center; background-repeat: no-repeat; background-size: cover;">
<h1 class="display-4" style="position:relative; top:5%;"><p class="text-center">제 품 등 록</p></h1>
<div class="container" style="position:relative; top:10%;">
        <form method="post" class="post-form my-3" id="info-form">
        {% csrf_token %}
        <!-- 오류표시 Start -->
        {% if form.errors %}
            <div class="alert alert-danger" role="alert">
            {% for field in form %}
                {% if field.errors %}
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
                {% endif %}
            {% endfor %}
            </div>
        {% endif %}
        <!-- 오류표시 End -->
        <div class="form-group" style="position:relative; margin-left:25%; ">
            <label for="asname" >고객명</label>
            <input type="text" class="form-control" name="asname" id="asname"
                   value="{{ form.name.value|default_if_none:'' }}" style="width:550px">
        </div>
        <div class="form-group" style="position:relative; margin-left:25%;">
            <label for="ph">전화번호</label>
            <input type="number" class="form-control" name="ph" id="ph"
                   value="{{ form.ph.value|default_if_none:'' }}" style="width:550px">
        </div>
        <div class="form-group" style="position:relative; margin-left:25%;">
            <label for="pronumber" >제품번호</label>
            <input type="text" class="form-control" name="pronumber" id="pronumber"
                   value="{{ form.name.value|default_if_none:'' }}" style="width:550px">
        </div>
        <button type="submit" class="btn btn-primary" style="display: block; margin: 0 auto; position:relative; top:50px;
        background-color:#0e0f0f; border-color:#0e0f0f; width: 550px; font-size:large; font-weight: 900; text-align:center;">제&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp출</button>
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }} m-2" id="msg" role="alert">
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}
        </form>
</div>
</div>

templates/oneup/as_list.html
{% extends 'base3.html' %}
{% load main_filter %}
{% block content %}
<div class="img-fluid" style="background-image: url('https://res.cloudinary.com/dgb2e2npb/image/upload/v1616501051/BG07_yupr0v.jpg');
      height: 100vh; background-position: center; background-repeat: no-repeat; background-size: cover;">
<div class="container my-3">
    <div class="row justify-content-between my-3"> <!-- 양쪽정렬 justify-content-between로 변경 -->
        <div class="col-2">
            <select class="form-control so">
                <option value="recent" {% if so == 'recent' %}selected{% endif %}>등록일시순</option>
                <option value="asname" {% if so == 'asname' %}selected{% endif %}>고객명순</option>
                <option value="pronu" {% if so == 'pronu' %}selected{% endif %}>제품번호순</option>
                <option value="assta" {% if so == 'assta' %}selected{% endif %}>A/S현황순</option>
            </select>
        </div>
        <div class="col-4 input-group">
            <input type="text" class="form-control kw" value="{{ kw|default_if_none:'' }}">
            <div class="input-group-append">
                <button class="btn btn-outline-secondary" type="button" id="btn_search">찾기</button>
            </div>
        </div>
    </div>
    <table class="table">
        <thead>
        <tr class="thead-dark">
            <th>번호</th>
            <th>고객명</th>
            <th>전화번호</th>
            <th>제품번호</th>
            <th>A/S현황</th>
            <th>통화녹음</th>
            <th>등록일시</th>
        </tr>
        </thead>
        <tbody>
        {% if as_list %}
        {% for as in as_list %}
        <tr>
            <td>
                <!-- 번호 = 전체건수 - 시작인덱스 - 현재인덱스 + 1 -->
                {{ as_list.paginator.count|sub:as_list.start_index|sub:forloop.counter0|add:1 }}
            </td>
            <td>{{ as.asname }}</td>
            <td>{{ as.ph }}</td>
            <td>{{ as.pronumber }}</td>
            <td>{{ as.assta }}</td>
            <td>{{ as.record }}</td>
            <td>{{ as.asdate }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">데이터가 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    <a href="{% url 'oneup:as_export' %}" class="btn btn-primary">추출하기</a>
    <!-- 페이징처리 시작 -->
    <ul class="pagination justify-content-center">
        <!-- 이전페이지 -->
        {% if as_list.has_previous %}
        <li class="page-item">
            <a class="page-link" data-page="{{ as_list.previous_page_number }}" href="#">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
        {% endif %}
        <!-- 페이지리스트 -->
        {% for page_number in as_list.paginator.page_range %}
        {% if page_number >= as_list.number|add:-5 and page_number <= as_list.number|add:5 %}
            {% if page_number == as_list.number %}
            <li class="page-item active" aria-current="page">
                <a class="page-link" data-page="{{ page_number }}" href="#">{{ page_number }}</a>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" data-page="{{ page_number }}" href="#">{{ page_number }}</a>
            </li>
            {% endif %}
        {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if as_list.has_next %}
        <li class="page-item">
            <a class="page-link" data-page="{{ as_list.next_page_number }}" href="#">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
        {% endif %}
    </ul>
    <!-- 페이징처리 끝 -->
</div>
</div>
<form id="searchForm" method="get" action="{% url 'oneup:after' %}">
    <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
    <input type="hidden" id="page" name="page" value="{{ page }}">
    <input type="hidden" id="so" name="so" value="{{ so }}">
</form>
{% endblock %}

{% block script %}
<script type='text/javascript'>
$(document).ready(function(){
    $(".page-link").on('click', function() {
        $("#page").val($(this).data("page"));
        $("#searchForm").submit();
    });

    $("#btn_search").on('click', function() {
        $("#kw").val($(".kw").val());
        $("#page").val(1);  // 검색버튼을 클릭할 경우 1페이지부터 조회한다.
        $("#searchForm").submit();
    });

    $(".so").on('change', function() {
        $("#so").val($(this).val());
        $("#page").val(1);
        $("#searchForm").submit();
    });
});
</script>
{% endblock %}

templates/oneup/deny.html
{% extends "base6.html" %}
{% block content %}
<!-- Modal -->

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">권한 오류</h5>
      </div>
      <div class="modal-body">
        사용 권한이 없습니다.
      </div>
      <div class="modal-footer">
          <a href="{% url 'oneup:main' %}" class="btn btn-primary">돌아가기</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block script %}
<script type='text/javascript'>
    $('#exampleModal').modal('show')
</script>
{% endblock %}

templates/oneup/logistics_list.html
{% extends 'base5.html' %}
{% load main_filter %}
{% block content %}
<div style="background-image: url('https://res.cloudinary.com/dgb2e2npb/image/upload/v1616503077/BG10_auxbku.jpg');
      height: 100vh; background-position: center; background-repeat: no-repeat; background-size: cover;">
<div class="container my-3">
    <div class="row justify-content-between my-3"> <!-- 양쪽정렬 justify-content-between로 변경 -->
        <div class="col-2">
            <select class="form-control so">
                <option value="logn" {% if so == 'logn' %}selected{% endif %}>제품명순</option>
                <option value="logsn" {% if so == 'logsn' %}selected{% endif %}>시리얼넘버순</option>
                <option value="wh" {% if so == 'wh' %}selected{% endif %}>보관창고순</option>
                <option value="dis" {% if so == 'dis' %}selected{% endif %}>총판순</option>
                <option value="agen" {% if so == 'agen' %}selected{% endif %}>대리점순</option>
                <option value="logcu" {% if so == 'logcu' %}selected{% endif %}>고객순</option>
            </select>
        </div>
        <div class="col-4 input-group">
            <input type="text" class="form-control kw" value="{{ kw|default_if_none:'' }}">
            <div class="input-group-append">
                <button class="btn btn-outline-secondary" type="button" id="btn_search">찾기</button>
            </div>
        </div>
    </div>
    <table class="table">
        <thead>
        <tr class="thead-dark">
            <th>번호</th>
            <th>제품명</th>
            <th>시리얼넘버</th>
            <th>보관창고</th>
            <th>총판</th>
            <th>대리점</th>
            <th>고객</th>
        </tr>
        </thead>
        <tbody>
        {% if logistics_list %}
        {% for logistics in logistics_list %}
        <tr>
            <td>
                <!-- 번호 = 전체건수 - 시작인덱스 - 현재인덱스 + 1 -->
                {{ logistics_list.paginator.count|sub:logistics_list.start_index|sub:forloop.counter0|add:1 }}
            </td>
            <td>{{ logistics.logname }}</td>
            <td>{{ logistics.logsn }}</td>
            <td>{{ logistics.wh }}</td>
            <td>{{ logistics.dis }}</td>
            <td>{{ logistics.agen }}</td>
            <td>{{ logistics.logcustom }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">데이터가 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    <a href="{% url 'oneup:log_export' %}" class="btn btn-primary">추출하기</a>
    <!-- 페이징처리 시작 -->
    <ul class="pagination justify-content-center">
        <!-- 이전페이지 -->
        {% if logistics_list.has_previous %}
        <li class="page-item">
            <a class="page-link" data-page="{{ logistics_list.previous_page_number }}" href="#">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
        {% endif %}
        <!-- 페이지리스트 -->
        {% for page_number in logistics_list.paginator.page_range %}
        {% if page_number >= logistics_list.number|add:-5 and page_number <= logistics_list.number|add:5 %}
            {% if page_number == logistics_list.number %}
            <li class="page-item active" aria-current="page">
                <a class="page-link" data-page="{{ page_number }}" href="#">{{ page_number }}</a>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" data-page="{{ page_number }}" href="#">{{ page_number }}</a>
            </li>
            {% endif %}
        {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if logistics_list.has_next %}
        <li class="page-item">
            <a class="page-link" data-page="{{ logistics_list.next_page_number }}" href="#">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
        {% endif %}
    </ul>
    <!-- 페이징처리 끝 -->
</div>
</div>
<form id="searchForm" method="get" action="{% url 'oneup:logistics' %}">
    <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
    <input type="hidden" id="page" name="page" value="{{ page }}">
    <input type="hidden" id="so" name="so" value="{{ so }}">
</form>
{% endblock %}

{% block script %}
<script type='text/javascript'>
$(document).ready(function(){
    $(".page-link").on('click', function() {
        $("#page").val($(this).data("page"));
        $("#searchForm").submit();
    });

    $("#btn_search").on('click', function() {
        $("#kw").val($(".kw").val());
        $("#page").val(1);  // 검색버튼을 클릭할 경우 1페이지부터 조회한다.
        $("#searchForm").submit();
    });

    $(".so").on('change', function() {
        $("#so").val($(this).val());
        $("#page").val(1);
        $("#searchForm").submit();
    });
});
</script>
{% endblock %}

templates/oneup/main.html
{% extends "base6.html" %}
{% block content %}
<div style="background-image: url('https://res.cloudinary.com/dgb2e2npb/image/upload/v1616501051/BG05_gyg80l.jpg');
      height: 100vh; background-position: center; background-repeat: no-repeat; background-size: cover;">
<div style="position:relative; top:25%;">
<div class="row row-cols-1 row-cols-md-4 g-4">
  <div class="col">
    <div class="card">
      <img src="https://res.cloudinary.com/dgb2e2npb/image/upload/v1616503077/01_Outsourcing_s21e2j.jpg" class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title">아웃소싱</h5>
        <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
          <a href="{% url 'oneup:outsourcing' %}" class="btn btn-primary">아웃소싱</a>
      </div>
    </div>
  </div>
  <div class="col">
    <div class="card">
      <img src="https://res.cloudinary.com/dgb2e2npb/image/upload/v1616503078/02_Production_k1esxq.jpg" class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title">제조공정</h5>
        <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
          <a href="{% url 'oneup:manufacture' %}" class="btn btn-success">제조공정</a>
      </div>
    </div>
  </div>
  <div class="col">
    <div class="card">
      <img src="https://res.cloudinary.com/dgb2e2npb/image/upload/v1616503078/03_Logistics_yhnuwd.jpg" class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title">유 통</h5>
        <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content.</p>
          <a href="{% url 'oneup:logistics' %}" class="btn btn-info">유통</a>
      </div>
    </div>
  </div>
  <div class="col">
    <div class="card">
      <img src="https://res.cloudinary.com/dgb2e2npb/image/upload/v1616503323/04_AS_htbtic.jpg" class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title">애프터 서비스</h5>
        <p class="card-text">This is a longer card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
          <a href="{% url 'oneup:after' %}" class="btn btn-danger">A/S</a>
      </div>
    </div>
  </div>
</div>
</div>



{% endblock %}


<!--&lt;!&ndash;<div class="img-fluid" style="background-image: url('https://res.cloudinary.com/dgb2e2npb/image/upload/v1616495167/BG03_df5jno.jpg');&ndash;&gt;-->
<!--&lt;!&ndash;      height: 100vh; background-position: center; background-repeat: no-repeat; background-size: cover;">&ndash;&gt;-->
<!--<a href="{% url 'oneup:outsourcing' %}" class="btn btn-primary">아웃소싱</a>-->
<!--<a href="{% url 'oneup:manufacture' %}" class="btn btn-success">제조공정</a>-->
<!--<a href="{% url 'oneup:logistics' %}" class="btn btn-info">유통</a>-->
<!--<a href="{% url 'oneup:after' %}" class="btn btn-danger">A/S</a>-->
<!--</div>-->