common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from oneup import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('oneup/', include('oneup.urls')),
    path('common/', include('common.urls')),
]

oneup/urls.py
from django.urls import path

from . import views

app_name = 'oneup'

urlpatterns = [
    path('outsourcing/', views.index, name='outsourcing'),
    path('manufacture/', views.manufacturer, name='manufacture'),
    path('logistics/', views.logistics, name='logistics'),
    path('as/', views.after, name='after'),
    path('main/', views.main, name='main'),
    path('deny/', views.deny, name='deny'),
    path('as_service/', views.as_create, name='as_create'),
    path('export1/', views.export1, name='out_export'),
    path('export2/', views.export2, name='make_export'),
    path('export3/', views.export3, name='log_export'),
    path('export4/', views.export4, name='as_export'),
    ]

common/models.py
from django.db import models

# Create your models here.

common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserForm(UserCreationForm):
    email = forms.EmailField(label="이메일")

    class Meta:
        model = User
        fields = ("username", "email")

common/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from common.forms import UserForm


def signup(request):
    """
    계정생성
    """
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('common:login')
    else:
        form = UserForm()
    return render(request, 'common/signup.html', {'form': form})

templates/common/login.html
{% extends "base4.html" %}
{% block content %}
<div class="img-fluid" style="background-image: url('https://res.cloudinary.com/dgb2e2npb/image/upload/v1616495167/BG02_seirwp.jpg');
      height: 100vh; background-position: center; background-repeat: no-repeat; background-size: cover;">
<div class="container my-3" >
    <div class="row" >
        <div class="col-4" style="position:relative; top:120px; margin-left:15%">
            <h4>로그인</h4>
        </div>
        <div class="col-8 text-right" style="position:relative; margin-top:7%; margin-left:20%">
            <span>또는 <a href="{% url 'common:signup' %}">계정을 만드세요.</a></span>
        </div>
    </div>
    <form method="post" class="post-form" action="{% url 'common:login' %}" style="position:relative; top:50px;">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="username" style="margin-left:15%">사용자ID</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}" style="width:700px; margin-left:15%">
        </div>
        <div class="form-group">
            <label for="password" style="margin-left:15%">비밀번호</label>
            <input type="password" class="form-control" name="password" id="password"
                   value="{{ form.password.value|default_if_none:'' }}" style="width:700px; margin-left:15%">
        </div>
        <button type="submit" class="btn btn-primary" style="margin-left:15%">로그인</button>
    </form>
</div>
</div>

<!-- Background image -->
{% endblock %}

templates/common/signup.html
{% extends "base4.html" %}
{% block content %}
<div class="container my-3">
    <div class="row my-3">
        <div class="col-4">
            <h4>계정생성</h4>
        </div>
        <div class="col-8 text-right">
            <span>또는 <a href="{% url 'common:login' %}">로그인 하세요.</a></span>
        </div>
    </div>
    <form method="post" class="post-form">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="username">사용자 이름</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password1">비밀번호</label>
            <input type="password" class="form-control" name="password1" id="password1"
                   value="{{ form.password1.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password2">비밀번호 확인</label>
            <input type="password" class="form-control" name="password2" id="password2"
                   value="{{ form.password2.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="email">이메일</label>
            <input type="text" class="form-control" name="email" id="email"
                   value="{{ form.email.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">생성하기</button>
    </form>
</div>
{% endblock %}